server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false # A discovery server doesn't register with itself
    fetch-registry: false # It also doesn't fetch a registry from itself